app/flask_app/models/todo.py
from flask_app.utils.db import db

class Todo(db.Model):
    """Model to persisting the data in a database"""

    __tablename__ =  'todo'

    id = db.Column(db.Integer, primary_key=True)
    description = db.Column(db.String(100), nullable=False)
    complete = db.Column(db.Boolean, default=False)

    def __init__(self, description, complete=False):
        self.description = description
        self.complete = complete

app/flask_app/__init__.py
from flask import Flask
from flask_app.views.todos import todos
from flask_app.utils.db import db
from flask_app.config import DATABASE_CONNECTION_URI, SECRET_KEY

app = Flask(__name__)

app.secret_key = SECRET_KEY
app.config['SQLALCHEMY_DATABASE_URI'] = DATABASE_CONNECTION_URI
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db.init_app(app)

app.register_blueprint(todos)

app/flask_app/views/todos.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_app.models.todo import Todo
from flask_app.utils.db import db
from flask_app.config import app_name

todos = Blueprint('todos', __name__)

@todos.route("/hello")
def hello():
    """route for testing the environment variables"""

    name = app_name
    
    if app_name:
        return f"Hello from {name} running in a Docker container behind Nginx! change"

    return "Hello from Flask"

@todos.route('/')
def index():
    """list all todo records"""

    todos = Todo.query.all()
    return render_template('index.html', todos=todos)


@todos.route('/new', methods=['POST'])
def add_todo():
    """create a new todo record"""
    
    description = request.form.get('description')
    complete = True if request.form.get('complete') else False
    todo = Todo(description, complete)
    db.session.add(todo)
    
    db.session.commit()
    
    flash('Todo created successfully')
    
    return redirect(url_for('todos.index'))


@todos.route('/update/<id>', methods=['GET', 'POST'])
def update_todo(id):
    """update a todo with a specific id"""

    todo = Todo.query.get(id)
    if request.method == 'POST':
        todo.description = request.form.get('description')
        todo.complete = True if request.form.get('complete') else False
        
        db.session.commit()
        
        flash('Todo updated successfully')
        
        return redirect(url_for('todos.index'))
    return render_template('update.html', todo=todo)


@todos.route('/delete/<id>')
def delete_todo(id):
    """drop a todo record with specific id"""

    todo = Todo.query.get(id)
    db.session.delete(todo)

    db.session.commit()
    
    flash('Todo deleted successfully')

    return redirect(url_for('todos.index'))


@todos.route('/about')
def about():
    """about this project"""

    return render_template('about.html')

app/flask_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-white">About this app</h1>
<h2 class="text-white">Simple project to practie docker learning</h2>
<p class="text-white">You can CREATE, READ, UPDATE and DELETE activities to do</p>
<p class="text-white">Type activities that you have to do and click in Create button to save it</p>
<p class="text-white">Any time you can update or delete them</p>
<p class="text-white">Enjoys it, and God bless you</p>
{% endblock content %}

app/flask_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO List</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
    {% include('partials/_navbar.html') %}
    
    <div class="container p-2">
        {% block content%}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% block extra_js%}
    {% endblock extra_js %}
</body>
</html>

app/flask_app/templates/index.html
{% extends 'base.html' %}
{% block content%}

    <div class="row">
        <div class="col-md-5">
            {% include('partials/_message.html')%}
            {% include('partials/_todoForm.html')%}
        </div>
        <div class="col-md-7">        
            {% for todo in todos %}
                <div class="card mb-1 text-black bg-light">
                    <div class="d-flex justify-content-between">
                        <div class="card-body">
                            <h5>{{todo.description}}</h5>
                            <p>{{todo.complete}}</p>
                            <div>
                                <a href="{{ url_for('todos.update_todo',id=todo.id)}}" class="btn bg-black text-white btn-sm rounded-0">Update</a>
                                <a href="{{ url_for('todos.delete_todo', id=todo.id)}}" class="btn btn-danger btn-sm rounded-0">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

app/flask_app/templates/partials/_message.html
{% with messages = get_flashed_messages() %}
    {% if messages%}
        {% for message in messages%}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
        {% endfor%}
    {% endif %}
{% endwith%}

app/flask_app/templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="/">TODO List</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="/about">About</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/flask_app/templates/partials/_todoForm.html
<form action="/new" method="POST" class="card bg-light text-dark">
    <div class="car-body p-4">
        <div class="mb-3">
            <label for="description">Write the Todo description:</label>
            <input type="text" name="description" required placeholder="write the description" class="form-control rounded-0 bg-light border-0 text-black">
        </div>
        
        <div class="mb-3">
            <label for="complete">complete?:</label>
            <input type="checkbox" name="complete" value=1 >
        </div>
        <button class="btn btn-primary">Save</button>
    </div>
</form>

app/flask_app/templates/update.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md offset-md-4">
            <form action="/update/{{todo.id}}" method="POST" class="card bg-light text-dark">
                <div class="card-body p-4">
                    <div class="mb-3">
                        <label for="description">Update your description:</label>
                        <input type="text" name="description" required placeholder="write the description" class="form-control rounded-0 bg-light border-0 text-black" value='{{todo.description}}' >
                    </div>
                    <div class="mb-3">
                        <label for="complete">complete?:</label>
                        {% if todo.complete %}
                            <input type="checkbox" name="complete" checked>
                        {% else %}
                            <input type="checkbox" name="complete">
                        {% endif %}
                    </div>
                    
                    <button class="btn btn-secondary">Update</button>
                </div>
        
            </form>
        </div>
    </div>
{% endblock content%}